## Import Essential Libraries...

In [2]:
import numpy as np
import pandas as pd

## Perform Data Cleaning...

In [3]:
# Import data
data = pd.read_csv("football_data.csv", sep = ",")
data.head(7)

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
5,5,183277,E. Hazard,27,https://cdn.sofifa.org/players/4/19/183277.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,91,Chelsea,...,91.0,34.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0,€172.1M
6,6,177003,L. Modrić,32,https://cdn.sofifa.org/players/4/19/177003.png,Croatia,https://cdn.sofifa.org/flags/10.png,91,91,Real Madrid,...,84.0,60.0,76.0,73.0,13.0,9.0,7.0,14.0,9.0,€137.4M

In [4]:
data.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

In [5]:
# Selecting numeric-columns from the given data.
tmp_data = data[['ID', 'Name', 'Overall', 'Potential', 'Value', 'Wage', 'Special', 'Weak Foot',
       'Skill Moves', 'Position', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower', 
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes']]

tmp_data.head()

,ID,Name,Overall,Potential,Value,Wage,Special,Weak Foot,Skill Moves,Position,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,158023,L. Messi,94,94,€110.5M,€565K,2202,4.0,4.0,RF,...,75.0,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0
1,20801,Cristiano Ronaldo,94,94,€77M,€405K,2228,4.0,5.0,ST,...,85.0,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0
2,190871,Neymar Jr,92,93,€118.5M,€290K,2143,5.0,5.0,LW,...,81.0,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0
3,193080,De Gea,91,93,€72M,€260K,1471,3.0,1.0,GK,...,40.0,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0
4,192985,K. De Bruyne,91,92,€102M,€355K,2281,5.0,4.0,RCM,...,79.0,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0

In [6]:
pd.options.mode.chained_assignment = None
def str_to_float(x): 
    x['Value'] = x['Value'][1:-1] # Defining this function would be longer than just applying "lambda" directly.

# Time to clean some of the columns
# Convert "Value" and "Wage" to numeric.
tmp_data['Value'] = tmp_data['Value'].apply(lambda x:np.float32(x[1:-1]) if len(x)>2 else 0.)
tmp_data['Wage'] = tmp_data['Wage'].apply(lambda x:np.float32(x[1:-1]) if len(x)>2 else 0.)

tmp_data = tmp_data[tmp_data['Club'].notnull()]

In [8]:
# NOw filter out GoalKeepers from the data and make a different column called "performance" according to the position of player.
tmp_data = tmp_data.assign(GK=lambda x: (x['GKDiving'] + x['GKHandling'] + x['GKKicking'] + x['GKPositioning'] + x['GKReflexes'])/5.)

In [9]:
tmp_data

,ID,Name,Overall,Potential,Value,Wage,Special,Weak Foot,Skill Moves,Position,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,GK
0,158023,L. Messi,94,94,110.5,565.0,2202,4.0,4.0,RF,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,10.8
1,20801,Cristiano Ronaldo,94,94,77.0,405.0,2228,4.0,5.0,ST,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,11.6
2,190871,Neymar Jr,92,93,118.5,290.0,2143,5.0,5.0,LW,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,11.8
3,193080,De Gea,91,93,72.0,260.0,1471,3.0,1.0,GK,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,88.8
4,192985,K. De Bruyne,91,92,102.0,355.0,2281,5.0,4.0,RCM,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,11.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,47,65,60.0,1.0,1307,2.0,2.0,CM,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,9.4
18203,243165,N. Christoffersson,47,63,60.0,1.0,1098,2.0,2.0,ST,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,9.0
18204,241638,B. Worman,47,67,60.0,1.0,1189,3.0,2.0,ST,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,8.0
18205,246268,D. Walker-Rice,47,66,60.0,1.0,1228,3.0,2.0,RW,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,10.2
18206,246269,G. Nugent,46,66,60.0,1.0,1321,3.0,2.0,CM,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,11.0

In [10]:
# Drop those rows where player are not assigned to any position type.
tmp_data = tmp_data[tmp_data['Position'].notnull()]

In [11]:
# Change position ratings to numericals tmp_data['Performance'] = 
tmp_data['Performance'] = tmp_data.apply(lambda x: np.int32(x[x['Position']][:-2]) if x['Position'] != 'GK' else x[x['Position']], axis = 1)

In [12]:
tmp_data

,ID,Name,Overall,Potential,Value,Wage,Special,Weak Foot,Skill Moves,Position,...,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,GK,Performance
0,158023,L. Messi,94,94,110.5,565.0,2202,4.0,4.0,RF,...,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,10.8,93.0
1,20801,Cristiano Ronaldo,94,94,77.0,405.0,2228,4.0,5.0,ST,...,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,11.6,91.0
2,190871,Neymar Jr,92,93,118.5,290.0,2143,5.0,5.0,LW,...,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,11.8,89.0
3,193080,De Gea,91,93,72.0,260.0,1471,3.0,1.0,GK,...,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,88.8,88.8
4,192985,K. De Bruyne,91,92,102.0,355.0,2281,5.0,4.0,RCM,...,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,11.2,87.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,47,65,60.0,1.0,1307,2.0,2.0,CM,...,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,9.4,45.0
18203,243165,N. Christoffersson,47,63,60.0,1.0,1098,2.0,2.0,ST,...,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,9.0,45.0
18204,241638,B. Worman,47,67,60.0,1.0,1189,3.0,2.0,ST,...,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,8.0,45.0
18205,246268,D. Walker-Rice,47,66,60.0,1.0,1228,3.0,2.0,RW,...,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,10.2,47.0
18206,246269,G. Nugent,46,66,60.0,1.0,1321,3.0,2.0,CM,...,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,11.0,45.0

In [13]:
tmp_data.select_dtypes(include= ["number"]).columns

Index(['ID', 'Overall', 'Potential', 'Value', 'Wage', 'Special', 'Weak Foot',
       'Skill Moves', 'Crossing', 'Finishing', 'HeadingAccuracy',
       'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy',
       'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility',
       'Reactions', 'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength',
       'LongShots', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle',
       'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'GK', 'Performance'],
      dtype='object')

In [14]:
# Prepare data for CASE-I
data_case1 = tmp_data[['ID', 'Name', 'Overall', 'Potential', 'Weak Foot',
       'Skill Moves', 'Performance', 'Crossing','Finishing', 'HeadingAccuracy', 'ShortPassing',
       'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle']]
data_case2 = tmp_data[['ID', 'Name', 'Overall', 'Potential', 'Value', 'Wage', 'Special', 'Weak Foot',
       'Skill Moves', 'Performance', 'Crossing','Finishing', 'HeadingAccuracy', 'ShortPassing',
        'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle']]
# Prepare data for CASE-II

In [15]:
# Show data for CASE-I and II
data_case1#.select_dtypes(include= ["number"]).columns

,ID,Name,Overall,Potential,Weak Foot,Skill Moves,Performance,Crossing,Finishing,HeadingAccuracy,...,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,158023,L. Messi,94,94,4.0,4.0,93.0,84.0,95.0,70.0,...,94.0,48.0,22.0,94.0,94.0,75.0,96.0,33.0,28.0,26.0
1,20801,Cristiano Ronaldo,94,94,4.0,5.0,91.0,84.0,94.0,89.0,...,93.0,63.0,29.0,95.0,82.0,85.0,95.0,28.0,31.0,23.0
2,190871,Neymar Jr,92,93,5.0,5.0,89.0,79.0,87.0,62.0,...,82.0,56.0,36.0,89.0,87.0,81.0,94.0,27.0,24.0,33.0
3,193080,De Gea,91,93,3.0,1.0,88.8,17.0,13.0,21.0,...,12.0,38.0,30.0,12.0,68.0,40.0,68.0,15.0,21.0,13.0
4,192985,K. De Bruyne,91,92,5.0,4.0,87.0,93.0,82.0,55.0,...,91.0,76.0,61.0,87.0,94.0,79.0,88.0,68.0,58.0,51.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,47,65,2.0,2.0,45.0,34.0,38.0,40.0,...,38.0,46.0,46.0,39.0,52.0,43.0,45.0,40.0,48.0,47.0
18203,243165,N. Christoffersson,47,63,2.0,2.0,45.0,23.0,52.0,52.0,...,42.0,47.0,16.0,46.0,33.0,43.0,42.0,22.0,15.0,19.0
18204,241638,B. Worman,47,67,3.0,2.0,45.0,25.0,40.0,46.0,...,45.0,32.0,15.0,48.0,43.0,55.0,41.0,32.0,13.0,11.0
18205,246268,D. Walker-Rice,47,66,3.0,2.0,47.0,44.0,50.0,39.0,...,34.0,33.0,22.0,44.0,47.0,50.0,46.0,20.0,25.0,27.0
18206,246269,G. Nugent,46,66,3.0,2.0,45.0,41.0,34.0,46.0,...,32.0,56.0,42.0,34.0,49.0,33.0,43.0,40.0,43.0,50.0

In [16]:
data_case2.head(7)

,ID,Name,Overall,Potential,Value,Wage,Special,Weak Foot,Skill Moves,Performance,...,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,158023,L. Messi,94,94,110.5,565.0,2202,4.0,4.0,93.0,...,94.0,48.0,22.0,94.0,94.0,75.0,96.0,33.0,28.0,26.0
1,20801,Cristiano Ronaldo,94,94,77.0,405.0,2228,4.0,5.0,91.0,...,93.0,63.0,29.0,95.0,82.0,85.0,95.0,28.0,31.0,23.0
2,190871,Neymar Jr,92,93,118.5,290.0,2143,5.0,5.0,89.0,...,82.0,56.0,36.0,89.0,87.0,81.0,94.0,27.0,24.0,33.0
3,193080,De Gea,91,93,72.0,260.0,1471,3.0,1.0,88.8,...,12.0,38.0,30.0,12.0,68.0,40.0,68.0,15.0,21.0,13.0
4,192985,K. De Bruyne,91,92,102.0,355.0,2281,5.0,4.0,87.0,...,91.0,76.0,61.0,87.0,94.0,79.0,88.0,68.0,58.0,51.0
5,183277,E. Hazard,91,91,93.0,340.0,2142,4.0,4.0,88.0,...,80.0,54.0,41.0,87.0,89.0,86.0,91.0,34.0,27.0,22.0
6,177003,L. Modrić,91,91,67.0,420.0,2280,4.0,4.0,88.0,...,82.0,62.0,83.0,79.0,92.0,82.0,84.0,60.0,76.0,73.0

In [17]:
# Normalizing the data, with each column being in the range 0-100
def normalizer(x):
    return np.round(100*(x - min(x))/(max(x) - min(x)), 3)

In [18]:
# Transform both data_case1 and data_case2
data_case1_normalized = data_case1.iloc[:, 2:].apply(normalizer)# by-default , axis = 0
data_case2_normalized = data_case2.iloc[:, 2:].apply(normalizer)# by-default , axis = 0
data_case1_normalized['ID'] = data_case1.ID
data_case1_normalized['Name'] = data_case1.Name
data_case2_normalized['ID'] = data_case2.ID
data_case2_normalized['Name'] = data_case2.Name

__Why NOrmalization is required for CLUSTERING?__
1. https://stats.stackexchange.com/questions/89809/is-it-important-to-scale-data-before-clustering
2. https://stackoverflow.com/questions/20027645/does-kmeans-normalize-features-automatically-in-sklearn
3. https://stackoverflow.com/questions/63929598/for-dbscan-python-is-it-mandatory-to-do-standardization-and-normalization-both
4. https://stackoverflow.com/questions/15777201/why-vector-normalization-can-improve-the-accuracy-of-clustering-and-classificati

In [19]:
#Save both Normalized and Non-Normalized data for both cases.
data_case1.to_csv('Data_Case1.csv', sep = ",", encoding='utf-8')
data_case2.to_csv('Data_Case2.csv', sep = ",", encoding='utf-8')
data_case1_normalized.to_csv('Data_Case1_normalized.csv', sep = ",", encoding='utf-8')
data_case2_normalized.to_csv('Data_Case2_normalized.csv', sep = ",", encoding='utf-8')